### ISSUE TITLE
哈喽大佬，GTAOL恶意值查询工具用不了了，冬季DLC更新后失效了，恶意值始终是0 。

### ISSUE THREAD

**Issue by Beakman-Yang** [SkyD666/SmartScreenSnapper#1]

**Comment by SkyD666** [comment]
勿急，今晚发版

**Comment by SkyD666** [comment]
[Act3SpeedrunTool-v7.0.1.68.zip](https://github.com/SkyD666/SmartScreenSnapper/files/13661724/Act3SpeedrunTool-v7.0.1.68.zip)
