### ISSUE TITLE
你好，我用4K显示器，用热键进行自由截图，也就是矩形截图，屏幕会放大只显示屏幕左上角的部分

### ISSUE THREAD

**Issue by AliSwitch** [SkyD666/SmartScreenSnapper#3]
用这个方法实际能截取的范围大约2500*1400，且无法触发自动保存
目前只有使用全屏截图是可以正常截图并自动保存的。
如果可以修复的话，建议再加一个选项，自由截图松开鼠标后立即保存，而不是按ENTER再保存。

**Comment by SkyD666** [comment]
对于高DPI的问题，下面的版本已修复
https://github.com/SkyD666/SmartScreenSnapper/releases/tag/2.1.0.0

对于自动保存的问题，您需要在下拉框选择要设置的功能，设置仅针对选择的功能
![2024-01-28 005358](https://github.com/SkyD666/SmartScreenSnapper/assets/32453770/e8e5201a-7e2c-41ee-b7d4-b6c2605bf2d9)

对于“自由截图松开鼠标后立即保存”，后续版本再支持

**Comment by AliSwitch** [comment]
> 对于高DPI的问题，下面的版本已修复 https://github.com/SkyD666/SmartScreenSnapper/releases/tag/2.1.0.0
> 
> 对于自动保存的问题，您需要在下拉框选择要设置的功能，设置仅针对选择的功能 ![2024-01-28 005358](https://private-user-images.githubusercontent.com/32453770/300192390-e8e5201a-7e2c-41ee-b7d4-b6c2605bf2d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MDQzOTAsIm5iZiI6MTcwNjQwNDA5MCwicGF0aCI6Ii8zMjQ1Mzc3MC8zMDAxOTIzOTAtZThlNTIwMWEtN2UyYy00MWVlLWI3ZDQtYjZjMjYwNWJmMmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDAxMDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzY2NTZhNjdlOTk5YjM3ZTA2YWQ2OWM0OTM3ZGNhMDg2MmU5YjlhNTllNmU2YmQ2NGI2MjllZjBkMWM4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UK4oFClybaiGDnYu5bondyBSB_iCMbc7uEz6Qn2QUdA)
> 
> 对于“自由截图松开鼠标后立即保存”，后续版本再支持

非常感谢，竟然时隔一年多连夜更新！然后再提一个小建议，录制GIF还行，尽量不要添加录屏功能·····电脑上能用来录屏的东西够多了，截图软件没必要再提供这个功能。
我之前用PICPICK，后来越来越臃肿，比较火的Snipaste也没有松开鼠标后立即保存，在GITHUB上搜索截图，对比了几十页，只有您这款软件最合适，衷心希望您能继续开发！再次感谢！

**Comment by SkyD666** [comment]
录屏确实还是需要专业软件来，例如obs这些

**Comment by AliSwitch** [comment]
> 对于高DPI的问题，下面的版本已修复 https://github.com/SkyD666/SmartScreenSnapper/releases/tag/2.1.0.0

不好意思，好像是只修复了自由截图？徒手截图和窗体控件截图还是会放大。

**Comment by AliSwitch** [comment]
> 录屏确实还是需要专业软件来，例如obs这些

![自由截图 - 2024-01-28_093326_666821](https://github.com/SkyD666/SmartScreenSnapper/assets/64070138/22d7ddfc-93d5-42eb-ae07-d8c920ecc5c5)
 自由截图还是会失真，我不懂代码，是否可能只是显示正常了，实际截取的还是异常的分辨率？

**Comment by SkyD666** [comment]
> > 对于高DPI的问题，下面的版本已修复 https://github.com/SkyD666/SmartScreenSnapper/releases/tag/2.1.0.0
> 
> 不好意思，好像是只修复了自由截图？徒手截图和窗体控件截图还是会放大。
> 
> 

好像这俩确实是忘了修

**Comment by SkyD666** [comment]
> > 录屏确实还是需要专业软件来，例如obs这些
> 
> ![自由截图 - 2024-01-28_093326_666821](https://github.com/SkyD666/SmartScreenSnapper/assets/64070138/22d7ddfc-93d5-42eb-ae07-d8c920ecc5c5)
>  自由截图还是会失真，我不懂代码，是否可能只是显示正常了，实际截取的还是异常的分辨率？

昨天在dpi 125的情况下没看见问题，今天我看看更高的dpi是不是正常

**Comment by SkyD666** [comment]
[SmartScreenSnapper.zip](https://github.com/SkyD666/SmartScreenSnapper/files/14075874/SmartScreenSnapper.zip)
试试这个，除了“自由截图松开鼠标后立即保存”，其他bug应该都修了

**Comment by AliSwitch** [comment]
> [SmartScreenSnapper.zip](https://github.com/SkyD666/SmartScreenSnapper/files/14075874/SmartScreenSnapper.zip) 试试这个，除了“自由截图松开鼠标后立即保存”，其他bug应该都修了

OK，截图没有问题了。
但是每次启动都会试图让我“更新”到2.1.0版本2333
加一个是否自动更新的设置选项还是有必要的。
再次感谢！

**Comment by SkyD666** [comment]
https://github.com/SkyD666/SmartScreenSnapper/releases/tag/2.3.0.0

![2024-01-29_161149_367355](https://github.com/SkyD666/SmartScreenSnapper/assets/32453770/1d3af24d-5725-43a6-a2a7-848629f5406b)
